YouPizza/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using YouPizza.Data.Repository.IRepository;
using YouPizza.Model;

namespace YouPizza.Areas.Admin.Controllers;

[Area("Admin")]
[Controller]
public class CategoryController : Controller
{
    // GET
    private readonly IUnitOfWork _unitOfWork;

    public CategoryController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        IEnumerable<Category> objList = _unitOfWork.Category.GetAll();
        return View(objList);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Category obj)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Category.Add(obj);
            _unitOfWork.Category.Save();
            TempData["success"] = "Category created successfully";
            return RedirectToAction("Index");
        }

        return View(obj);
    }

    public IActionResult Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        var categoryFromDb = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
        if (categoryFromDb == null)
        {
            return NotFound();
        }


        return View(categoryFromDb);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Category obj)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Category.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category updated successfully";
            return RedirectToAction("Index");
        }

        return View(obj);
    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        var categoryFromDb = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);

        if (categoryFromDb == null)
        {
            return NotFound();
        }

        return View(categoryFromDb);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePOST(int? id)
    {
        var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }

        _unitOfWork.Category.Remove(obj);
        _unitOfWork.Category.Save();
        TempData["success"] = "Category deleted successfully";
        return RedirectToAction("Index");
    }
}

YouPizza/Areas/Admin/Controllers/ProductController.cs
using System.Net;
using System.Security.AccessControl;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using YouPizza.Data.Repository.IRepository;
using YouPizza.Model;
using YouPizza.Model.ViewModel;

namespace YouPizza.Areas.Admin.Controllers;

[Controller]
[Area("Admin")]
public class ProductController : Controller
{
    private readonly IUnitOfWork _db;
    private readonly IWebHostEnvironment _webHost;

    public ProductController(IUnitOfWork db, IWebHostEnvironment webHost)
    {
        _webHost = webHost;
        _db = db;
    }

    public IActionResult Index()
    {
        List<Product> ProductList = _db.Products
            .GetAll(includeProperties: "Category,IngredientsProduct,IngredientsProduct.Ingredients").ToList();
        return View(ProductList);
    }

    public IActionResult Upsert(int? id)
    {
        ProductVM obj = new ProductVM()
        {
            Product = new(),
            CategoryList = _db.Category.GetAll().Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString(),
            })
        };
        if (id == null)
        {
            return View(obj);
        }

        //this for edit
        obj.Product = _db.Products.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }

        return View(obj);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(ProductVM obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            obj.Product.Price = obj.Product.PriceSmall;
            string wwwRootPath = _webHost.WebRootPath;
            if (file != null)
            {
                // HOW TO COPY FILE IN C###

                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"img\Products");
                var extension = Path.GetExtension(file.FileName);

                if (obj.Product.ImageUrl != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists((oldImagePath)))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }

                obj.Product.ImageUrl = @"\img\Products\" + fileName + extension;
            }


            if (obj.Product.Id == 0)
            {
                //this is create
                _db.Products.Add(obj.Product);
            }
            else
            {
                //this is an update
                _db.Products.Update(obj.Product);
            }

            _db.Save();
            return RedirectToAction(nameof(Index));
        }

        return View(obj);
    }

    public IActionResult ManageIngredients(int id)
    {
        IngredientsProductVM obj = new IngredientsProductVM()
        {
            IngredientsProductsList = _db.IngredientsProduct.GetAll(includeProperties: "Product,Ingredients")
                .Where(u => u.ProductId == id),
            Product = _db.Products.GetFirstOrDefault(u => u.Id == id),
            IngredientsProduct = new IngredientsProduct()
            {
                ProductId = id,
            }
        };
        List<int> AssignedIngredientsList = obj.IngredientsProductsList.Select(u => u.IngredientsId).ToList();

        var tempList = _db.Ingredients.GetAll(u => !AssignedIngredientsList.Contains(u.Id)).ToList();

        obj.IngredientsList = tempList.Select(i => new SelectListItem
        {
            Text = i.Name,
            Value = i.Id.ToString()
        });
        Cookie cook = new Cookie();
        return View(obj);
    }


    [HttpPost]
    public IActionResult ManageIngredients(IngredientsProductVM obj)
    {
        if (obj.IngredientsProduct.IngredientsId != 0 && obj.IngredientsProduct.ProductId != 0)
        {
            _db.IngredientsProduct.Add(obj.IngredientsProduct);
            _db.Save();
        }

        return RedirectToAction(nameof(ManageIngredients), new { @id = obj.IngredientsProduct.ProductId });
    }

    [HttpPost]
    public IActionResult RemoveIngredients(int id, IngredientsProductVM obj)
    {
        int ProductId = obj.Product.Id;
        IngredientsProduct ingredientsProduct =
            _db.IngredientsProduct.GetFirstOrDefault(u => u.ProductId == ProductId && u.IngredientsId == id);
        _db.IngredientsProduct.Remove(ingredientsProduct);
        _db.Save();

        return RedirectToAction(nameof(ManageIngredients), new { @id = ProductId });
    }

    public IActionResult Delete(int id)
    {
        Product product = _db.Products.GetFirstOrDefault(p => p.Id == id);
        _db.Products.Remove(product);
        _db.Save();
        return RedirectToAction(nameof(Index));
    }
}

YouPizza/Areas/Admin/Controllers/SauceController.cs
using Microsoft.AspNetCore.Mvc;
using YouPizza.Data;
using YouPizza.Data.Repository.IRepository;
using YouPizza.Model;

namespace YouPizza.Areas.Admin.Controllers;


[Area("Admin")]
[Controller]
public class SauceController : Controller
{
    // GET
    private readonly IUnitOfWork _unitOfWork;

    public SauceController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        IEnumerable<Sauce> objList = _unitOfWork.Sauce.GetAll();
        return View(objList);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Sauce obj)
    {


        if (ModelState.IsValid)
        {
            _unitOfWork.Sauce.Add(obj);
            _unitOfWork.Sauce.Save();
            TempData["success"] = "Category created successfully";
            return RedirectToAction("Index");
        }

        return View(obj);
    }

    public IActionResult Edit(int? id)
    {

        if (id == null || id == 0)
        {
            return NotFound();
        }

        var categoryFromDb = _unitOfWork.Sauce.GetFirstOrDefault(u => u.Id == id);
        if (categoryFromDb == null)
        {
            return NotFound();
        }


        return View(categoryFromDb);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Sauce obj)
    {


        if (ModelState.IsValid)
        {
            _unitOfWork.Sauce.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category updated successfully";
            return RedirectToAction("Index");
        }

        return View(obj);
    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        var categoryFromDb = _unitOfWork.Sauce.GetFirstOrDefault(u => u.Id == id);

        if (categoryFromDb == null)
        {
            return NotFound();
        }

        return View(categoryFromDb);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePOST(int? id)
    {
        var obj = _unitOfWork.Sauce.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }

        _unitOfWork.Sauce.Remove(obj);
        _unitOfWork.Sauce.Save();
        TempData["success"] = "Category deleted successfully";
        return RedirectToAction("Index");
    }
}

YouPizza/Areas/Customer/Controllers/CartController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using YouPizza.Data.Repository.IRepository;
using YouPizza.Model;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using NuGet.Protocol;
using YouPizza.Model.ViewModel;
using YouPizza.Utility.SD;
using Stripe.Checkout;

namespace YouPizza.Areas.Customer.Controllers;

[Area("Customer")]
[Controller]
public class CartController : Controller
{
    // GET

    private readonly IUnitOfWork _db;


    public CartController(IUnitOfWork db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        ShoppingCartVM obj = new ShoppingCartVM();
        var value = HttpContext.Session.GetString("list");
        if (value != null)
        {
            obj.ListCart = JsonConvert.DeserializeObject<List<Product>>(value);
            obj.TotalPrice = obj.ListCart.Sum(item => item.Price);
        }


        return View(obj);
    }


   
    public IActionResult Remove(ShoppingCartVM cart)
    {
       
        var value = HttpContext.Session.GetString("list");
        List<Product> ProductList = JsonConvert.DeserializeObject<List<Product>>(value);
          ProductList.Remove(ProductList.Find(x => x.Id == cart.ListCart[0].Id && x.Size == cart.ListCart[0].Size ));

        HttpContext.Session.SetString("list", JsonConvert.SerializeObject(ProductList));

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Summary()
    {
        ShoppingCartVM summaryVm = new ShoppingCartVM();
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        if (claim != null)
        {
            var user = _db.ApplicationUsers.GetFirstOrDefault(u => u.Id == claim.Value);
            summaryVm.user.City = user.City;
            summaryVm.user.Name = user.Name;
            summaryVm.user.StreetAdress = user.StreetAdress;
            summaryVm.user.State = user.State;
            summaryVm.user.PostalCode = user.PostalCode;
            summaryVm.user.PhoneNumber = user.PhoneNumber;
        }
        else
        {
            summaryVm.user = new ApplicationUser();
        }

        var value = HttpContext.Session.GetString("list");
        summaryVm.ListCart = JsonConvert.DeserializeObject<List<Product>>(value);
        foreach (Product item in summaryVm.ListCart)
        {
            summaryVm.TotalPrice += item.Price;
        }

        return View(summaryVm);
    }

    [HttpPost]
    [ActionName("Summary")]
    [ValidateAntiForgeryToken]
    public IActionResult SummaryPOST(ShoppingCartVM orderSummary)
    {
        OrderSummary obj = new OrderSummary();
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        obj.Name = orderSummary.user.Name;
        obj.PhoneNumber = orderSummary.user.PhoneNumber;
        obj.StreetAdress = orderSummary.user.StreetAdress;
        obj.City = orderSummary.user.City;
        obj.State = orderSummary.user.State;
        obj.PostalCode = orderSummary.user.PostalCode;
        if (claim != null)
        {
            var user = _db.ApplicationUsers.GetFirstOrDefault(u => u.Id == claim.Value);
            obj.ApplicationUserId = user.Id;
        }
        var value = HttpContext.Session.GetString("list");
        IEnumerable<Product> productsList = JsonConvert.DeserializeObject<List<Product>>(value);
        obj.TotalPrice = productsList.Sum(u => u.Price);
      
        _db.OrderSummary.Add(obj);
        _db.Save();
      
        foreach (var item in productsList)
        {
           
            
            OrderDetail detail = new OrderDetail()
            {
                OrderId = obj.Id,
                Price = item.Price,
                ProductId = item.Id,
                Size = item.Size,
            };
            if (_db.OrderDetail.GetFirstOrDefault(u=>
                    u.OrderId==obj.Id && 
                    u.ProductId==item.Id &&
                    u.Price==item.Price)!=null)
            {
                _db.OrderDetail.GetFirstOrDefault(u =>
                    u.OrderId == obj.Id &&
                    u.ProductId == item.Id &&
                    u.Price == item.Price).Count++;
            }
            else
            {
                _db.OrderDetail.Add(detail);
            }
            _db.Save();
        }

        IEnumerable<OrderDetail> orderList = _db.OrderDetail.GetAll(u => u.OrderId == obj.Id,includeProperties:"Product");



        obj.OrderStatus = SD.Pending;
        obj.PaymentStatus = SD.Pending;
        

        _db.Save();

        //STRIPE PAYMENT


        var domain = "https://localhost:7033/";
        var options = new SessionCreateOptions
        {
            PaymentMethodTypes = new List<string>
            {
                "card"
            },
            LineItems = new List<SessionLineItemOptions>(),
            Mode = "payment",
            SuccessUrl = domain + $"customer/cart/OderConfirmation?id={obj.Id}",
            CancelUrl = domain + $"customer/cart/index",
        };

        foreach (var item in orderList)
        {
            var sessionLineItem = new SessionLineItemOptions
            {
                PriceData = new SessionLineItemPriceDataOptions()
                {
                    UnitAmount = (long)(item.Price * 100),
                    Currency = "pln",
                    ProductData = new SessionLineItemPriceDataProductDataOptions
                    {
                        Name = item.Product.Name,
                        Description = item.Product.Description
                    }
                },
                Quantity = item.Count
            };
            options.LineItems.Add(sessionLineItem);
        }
        
        var service = new SessionService();
        Session session = service.Create(options);
        _db.OrderSummary.GetFirstOrDefault(u=>u.Id==obj.Id).SessionId=session.Id;
        _db.OrderSummary.GetFirstOrDefault(u => u.Id == obj.Id).PaymentIntentId = session.PaymentIntentId;
        _db.Save();

        Response.Headers.Add("Location", session.Url);
        return new StatusCodeResult(303);
      
    }
    

    public IActionResult OderConfirmation(int id)
    {
        OrderSummary orderSummary = _db.OrderSummary.GetFirstOrDefault(u => u.Id == id);
        var service = new SessionService();
        Session session = service.Get(orderSummary.SessionId);
        if (session.PaymentStatus.ToLower() == "paid")
        {
            HttpContext.Session.Clear();
            orderSummary.PaymentAccepted = DateTime.Now.ToString("g");
            orderSummary.OrderStatus = "Paid";
            orderSummary.PaymentStatus = "Paid";
            _db.Save();
        }
        return View(orderSummary);
    }
 
}

YouPizza/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - YouPizza</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/YouPizza.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/flatly.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

</head>
<body>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">YouPizza</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            CMS
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li>
                                <a asp-area="Admin" asp-controller="Sauce" asp-action="Index" class="dropdown-item">Sauces</a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="Ingredients" asp-action="Index" class="dropdown-item">Ingredients</a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="dropdown-item">Categories</a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="dropdown-item">Products</a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="Order" asp-action="Index" class="dropdown-item">Orders</a>
                            </li>

                        </ul>
                    </li>
                    <ul class="nav justify-content-lg-start">

                        <li class="nav-item">
                            <a asp-area="Customer" asp-controller="Home" asp-action="Menu" class="nav-link">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="#">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Customer" asp-controller="Home" asp-action="AboutUs" class="nav-link">ABOUT US</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart"></i>
                            </a>
                        </li>
                    </ul>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">

</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
@await RenderSectionAsync("Scripts", required: false)

</body>
</html>