YouPizza/Areas/Admin/Controllers/IngredientsController.cs
using Microsoft.AspNetCore.Mvc;
using YouPizza.Data.Repository.IRepository;
using YouPizza.Model;

namespace YouPizza.Areas.Admin.Controllers;
[Controller]
[Area("Admin")]
public class IngredientsController : Controller
{
    
    // GET
    private readonly IUnitOfWork _unitOfWork;

    public IngredientsController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        IEnumerable<Ingredients> objList = _unitOfWork.Ingredients.GetAll();
        return View(objList);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create( Ingredients obj)
    {


        if (ModelState.IsValid)
        {
            _unitOfWork. Ingredients.Add(obj);
            _unitOfWork. Ingredients.Save();
            TempData["success"] = "Category created successfully";
            return RedirectToAction("Index");
        }

        return View(obj);
    }

    public IActionResult Edit(int? id)
    {

        if (id == null || id == 0)
        {
            return NotFound();
        }

        var categoryFromDb = _unitOfWork.Ingredients.GetFirstOrDefault(u => u.Id == id);
        if (categoryFromDb == null)
        {
            return NotFound();
        }


        return View(categoryFromDb);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit( Ingredients obj)
    {


        if (ModelState.IsValid)
        {
            _unitOfWork. Ingredients.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category updated successfully";
            return RedirectToAction("Index");
        }

        return View(obj);
    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        var categoryFromDb = _unitOfWork. Ingredients.GetFirstOrDefault(u => u.Id == id);

        if (categoryFromDb == null)
        {
            return NotFound();
        }

        return View(categoryFromDb);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePOST(int? id)
    {
        var obj = _unitOfWork. Ingredients.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }

        _unitOfWork. Ingredients.Remove(obj);
        _unitOfWork. Ingredients.Save();
        TempData["success"] = "Category deleted successfully";
        return RedirectToAction("Index");
    }
}

YouPizza/Areas/Admin/Views/Ingredients/Create.cshtml
@model YouPizza.Model.Ingredients
@{
    Layout = "_Layout";
}

<form method="post">
    <div class="border p-3 mt-4">
          <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">Create Ingredients</h2>
            <hr/>
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"> </span>
        </div>

        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
        <a asp-controller="Ingredients" asp-action="Index" class="btn btn-secondary">Back To List</a>

    </div>
</form>
@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

YouPizza/Areas/Admin/Views/Ingredients/Delete.cshtml
@model YouPizza.Model.Ingredients

@{
    Layout = "_Layout";
}

<form method="post" asp-action="DeletePOST">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Ingredients</h2>
            <hr/>
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" disabled class="form-control"/>

        </div>

        <button type="submit" class="btn btn-danger" style="width: 150px">Delete</button>
        <a asp-controller="Ingredients" asp-action="Index" class="btn btn-secondary">Back To List</a>

    </div>
</form>
@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

YouPizza/Areas/Admin/Views/Ingredients/Edit.cshtml
@model YouPizza.Model.Ingredients

@{
    Layout = "_Layout";
}

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Product</h2>
            <hr/>
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"> </span>
        </div>

        <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
        <a asp-controller="Ingredients" asp-action="Index" class="btn btn-secondary">Back To List</a>

    </div>
</form>
@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

YouPizza/Areas/Admin/Views/Ingredients/Index.cshtml
@model IEnumerable<YouPizza.Model.Ingredients>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Ingredients List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-action="Create" asp-controller="Ingredients" class="btn btn-primary">Add New Ingredients   <i class="bi bi-plus-circle"></i></a>
        </div>
    </div>
</div>

<br><br>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
    <tr>
        <th>
            Ingredients Name
        </th>
        
    </tr>
    </thead>
    <tbody>
    @foreach (var obj in Model)
    {
        <tr>
          

            <td width="30%">@obj.Name</td>
            <td class="">
                <div class="group w-75 btn-group">
                    <a asp-controller="Ingredients" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2"> Edit <i class="bi bi-pencil-square"></i></a>
                    <a asp-controller="Ingredients" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2"> Delete <i class="bi bi-x-square"></i></a>
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>